urlshortener/shortenersite/urls.py
from django.urls import re_path, path, include
from shortenersite import views

urlpatterns = [
    path('', views.index, name = 'home'),
    re_path(r'^(?P<short_id>\w{6})$', views.redirect_original, name = 'redirectoriginal'),
    path('makeshort/', views.shorten_url, name = 'shortenurl'),
]

urlshortener/urlshortener/urls.py
from django.contrib import admin 
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shortenersite.urls', 'shortenersite'), namespace='shortenersite'))
]

urlshortener/shortenersite/models.py
from django.db import models
 
# Create your models here.
class Urls(models.Model):
    short_id = models.SlugField(max_length=6,primary_key=True)
    httpurl = models.URLField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=0)
 
def __str__(self):
    return self.httpurl

urlshortener/shortenersite/views.py
from django.shortcuts import render, get_object_or_404
import random, string, json
from shortenersite.models import Urls
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.template.context_processors import csrf
 
def index(request):
    c = {}
    c.update(csrf(request))
    return render(None, 'shortenersite/index.html', c)
 
def redirect_original(request, short_id):
    url = get_object_or_404(Urls, pk=short_id) # get object, if not        found return 404 error
    url.count += 1
    url.save()
    return HttpResponseRedirect(url.httpurl)
 
def shorten_url(request):
    url = request.POST.get("url", '')
    if not (url == ''):
        short_id = get_short_code()
        b = Urls(httpurl=url, short_id=short_id)
        b.save()
 
        response_data = {}
        response_data['url'] = settings.SITE_URL + "/" + short_id
        return HttpResponse(json.dumps(response_data),  content_type="application/json")
    return HttpResponse(json.dumps({"error": "error occurs"}), content_type="application/json")
 
def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    # if the randomly generated short_id is used then generate next
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        try:
            temp = Urls.objects.get(pk=short_id)
        except:
            return short_id

urlshortener/shortenersite/templates/shortenersite/base.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}Welcome to mysite{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'shortenersite/css/custom.css' %}" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<script type="text/javascript">
    $(function () {
        $('#submitButton').click(function () {
            $.ajax({
                type: "POST",
                url: "/makeshort/",
                data: {
                    'url': $('#url').val(),
                    'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
                },
                success: returnSuccess,
                dataType: 'json'
            });
        });
    });

    function returnSuccess(data, textStatus, jqXHR) {
        if (data.url) {
            $('#url-result').text(data.url);
            $('#url').val("");
        } else {
            $('#url-result').text("Do not submit blank.");
        }

    }
</script>

<body>
    <div id="wrap">
        <header>
            <h1><a href="{% url 'shortenersite:home' %}">URL Shortner</a><small>by Igor Plyukhin</small></h1>
        </header>

        <div id="content">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>

</html>

urlshortener/shortenersite/templates/shortenersite/index.html
{% extends "shortenersite/base.html" %}

{% block title %}URL Shortner - Make your URL shorter!{% endblock %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-body">
        <div class="col-sm-9">
            <input type="text" name="url" id="url" class="form-control input-sm"
                placeholder="http://www.facebook.com" />
        </div>
        <div class="col-sm-3">
            {% csrf_token %}
            <button id="submitButton" class="btn btn-primary">Submit</button></p>
        </div>
    </div>
    <div class="panel-footer">
        <span id="url-result">Enter the URL above and click submit!</span>
        <button id="copyButton" class="btn btn-primary" onclick="myFunction()">Copy</button>
    </div>
</div>
<script type="text/javascript">
    function myFunction() {
        var copyText = document.getElementById("url-result");
        var textArea = document.createElement("textarea");
        textArea.value = copyText.textContent;
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand("Copy");
        textArea.remove();
    }
</script>
{% endblock %}